# Site settings
title: aupenn blog
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Random assortment of thoughts and interests.
baseurl: "/"
#baseurl: "/urban-theme" # the subpath of your site, e.g. /blog

url: "http://aupenn.tk" # the base hostname & protocol for your site
twitter_username: aupenn
#github_username:  aupenn

# Build settings
markdown: kramdown
permalink: pretty
