# Site settings
title: "aupenn's blog"
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  An assortment of thoughts about various interests.
baseurl: "/oriental"
#baseurl: "/urban-theme" # the subpath of your site, e.g. /blog

url: "https://aupenn.github.io/" # the base hostname & protocol for your site
#twitter_username: aupenn
github_username:  aupenn

# Build settings
markdown: kramdown
permalink: pretty
